# -*- coding: utf-8 -*-
"""Glasses_No_Glasses_Classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVz1HhJFtJTYkXKi4pRhqsBOll4-dL4S

# Glasses_No_Glasses_Classification

**Student ID:** 22F23625  
**Student Name:** Rayan Salim Rashid Al Mukhaini  
**Module:** Artificial Intelligence and Deep Learning  
**Assignment:** Binary Image Classification using Deep Learning  
**Platform:** Google Colab  
**Dataset:** Glasses or No Glasses - Kaggle

## Project Description

This project focuses on a binary image classification problem using deep learning. The selected dataset is the Glasses or No Glasses dataset from Kaggle. The main objective is to train a model that can classify whether a person in an image is wearing glasses or not wearing glasses.

The project will be implemented using Python in Google Colab. A Convolutional Neural Network model will be built from scratch, and a pre-trained deep learning model will also be used for comparison. The performance of both models will be evaluated using classification metrics such as accuracy, precision, recall, and F1-score.
"""

!pip install kaggle

from google.colab import files

files.upload()

# Create Kaggle directory
!mkdir -p ~/.kaggle

# Move kaggle.json file to Kaggle directory
!cp kaggle.json ~/.kaggle/

# Set permission for the Kaggle API file
!chmod 600 ~/.kaggle/kaggle.json

# Download the dataset from Kaggle
!kaggle datasets download -d jeffheaton/glasses-or-no-glasses

# Unzip the downloaded dataset
!unzip glasses-or-no-glasses.zip -d glasses_dataset

# Check dataset folders and files
import os

dataset_path = "glasses_dataset"

for root, dirs, files in os.walk(dataset_path):
    print("Folder:", root)
    print("Number of files:", len(files))
    print("-" * 50)

# List files in the main dataset folder
import os

main_path = "glasses_dataset"

print("Files and folders inside glasses_dataset:")
print(os.listdir(main_path))

# Read train and test CSV files
import pandas as pd

train_csv_path = "glasses_dataset/train.csv"
test_csv_path = "glasses_dataset/test.csv"

train_df = pd.read_csv(train_csv_path)
test_df = pd.read_csv(test_csv_path)

print("Train data shape:", train_df.shape)
print("Test data shape:", test_df.shape)

print("\nTrain CSV first 5 rows:")
display(train_df.head())

print("\nTest CSV first 5 rows:")
display(test_df.head())

# Show column names
print("Train columns:")
print(train_df.columns)

print("\nTest columns:")
print(test_df.columns)

# Check basic information about the training data
print(train_df.info())

print("\nMissing values:")
print(train_df.isnull().sum())

print("\nLabel distribution:")
print(train_df.iloc[:, -1].value_counts())

# Define the image folder path
images_path = "glasses_dataset/faces-spring-2020/faces-spring-2020"

# Check number of images
image_files = os.listdir(images_path)

print("Total images:", len(image_files))
print("First 10 image names:")
print(image_files[:10])

# Define the image folder path
images_path = "glasses_dataset/faces-spring-2020/faces-spring-2020"

# Create image filename based on id column
train_df["filename"] = train_df["id"].apply(lambda x: f"face-{int(x)}.png")

# Create full image path
train_df["image_path"] = train_df["filename"].apply(lambda x: os.path.join(images_path, x))

# Display first 5 rows to check
train_df[["id", "filename", "image_path", "glasses"]].head()

# Check if all image paths exist
train_df["image_exists"] = train_df["image_path"].apply(os.path.exists)

print("Existing images:", train_df["image_exists"].sum())
print("Missing images:", len(train_df) - train_df["image_exists"].sum())

# Show rows with missing images if any
train_df[train_df["image_exists"] == False].head()

# Display sample images with labels
import matplotlib.pyplot as plt
from PIL import Image

sample_df = train_df.sample(6, random_state=42)

plt.figure(figsize=(12, 6))

for i, row in enumerate(sample_df.itertuples(), 1):
    img = Image.open(row.image_path)

    plt.subplot(2, 3, i)
    plt.imshow(img)
    plt.axis("off")

    label_name = "Glasses" if row.glasses == 1 else "No Glasses"
    plt.title(label_name)

plt.tight_layout()
plt.show()

# Convert numeric labels to text labels for ImageDataGenerator
train_df["label"] = train_df["glasses"].apply(lambda x: "Glasses" if x == 1 else "No_Glasses")

# Display first 5 rows
train_df[["id", "filename", "glasses", "label"]].head()

# Split the dataset into training and validation sets
from sklearn.model_selection import train_test_split

train_data, val_data = train_test_split(
    train_df,
    test_size=0.2,
    random_state=42,
    stratify=train_df["label"]
)

print("Training data shape:", train_data.shape)
print("Validation data shape:", val_data.shape)

print("\nTraining label distribution:")
print(train_data["label"].value_counts())

print("\nValidation label distribution:")
print(val_data["label"].value_counts())

# Import ImageDataGenerator for image preprocessing
from tensorflow.keras.preprocessing.image import ImageDataGenerator

# Image settings
IMG_SIZE = 224
BATCH_SIZE = 32

# Data generator for training with augmentation
train_generator = ImageDataGenerator(
    rescale=1./255,
    rotation_range=15,
    zoom_range=0.1,
    horizontal_flip=True
)

# Data generator for validation without augmentation
val_generator = ImageDataGenerator(
    rescale=1./255
)

# Create training image data
train_images = train_generator.flow_from_dataframe(
    dataframe=train_data,
    x_col="image_path",
    y_col="label",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=True
)

# Create validation image data
val_images = val_generator.flow_from_dataframe(
    dataframe=val_data,
    x_col="image_path",
    y_col="label",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False
)

# Check class indices
print("Class indices:")
print(train_images.class_indices)

# Import TensorFlow and Keras layers
import tensorflow as tf
from tensorflow.keras import layers, models

# Build CNN model from scratch
cnn_model = models.Sequential([
    # First convolution block
    layers.Conv2D(32, (3, 3), activation="relu", input_shape=(IMG_SIZE, IMG_SIZE, 3)),
    layers.MaxPooling2D((2, 2)),

    # Second convolution block
    layers.Conv2D(64, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    # Third convolution block
    layers.Conv2D(128, (3, 3), activation="relu"),
    layers.MaxPooling2D((2, 2)),

    # Convert feature maps to one vector
    layers.Flatten(),

    # Fully connected layer
    layers.Dense(128, activation="relu"),

    # Dropout to reduce overfitting
    layers.Dropout(0.5),

    # Output layer for binary classification
    layers.Dense(1, activation="sigmoid")
])

# Show model architecture
cnn_model.summary()

# Compile CNN model
cnn_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Train CNN model
history_cnn = cnn_model.fit(
    train_images,
    validation_data=val_images,
    epochs=10
)

# Evaluate CNN model on validation data
cnn_loss, cnn_accuracy = cnn_model.evaluate(val_images)

print("CNN Validation Loss:", cnn_loss)
print("CNN Validation Accuracy:", cnn_accuracy)

# Plot CNN training and validation accuracy
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 5))
plt.plot(history_cnn.history["accuracy"], label="Training Accuracy")
plt.plot(history_cnn.history["val_accuracy"], label="Validation Accuracy")
plt.title("CNN Model Accuracy")
plt.xlabel("Epoch")
plt.ylabel("Accuracy")
plt.legend()
plt.show()

# Plot CNN training and validation loss
plt.figure(figsize=(8, 5))
plt.plot(history_cnn.history["loss"], label="Training Loss")
plt.plot(history_cnn.history["val_loss"], label="Validation Loss")
plt.title("CNN Model Loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.legend()
plt.show()

# Import MobileNetV2 pre-trained model
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.applications.mobilenet_v2 import preprocess_input

# Data generator for MobileNetV2 preprocessing
mobilenet_train_generator = ImageDataGenerator(
    preprocessing_function=preprocess_input,
    rotation_range=15,
    zoom_range=0.1,
    horizontal_flip=True
)

mobilenet_val_generator = ImageDataGenerator(
    preprocessing_function=preprocess_input
)

# Create MobileNetV2 training image data
mobilenet_train_images = mobilenet_train_generator.flow_from_dataframe(
    dataframe=train_data,
    x_col="image_path",
    y_col="label",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=True
)

# Create MobileNetV2 validation image data
mobilenet_val_images = mobilenet_val_generator.flow_from_dataframe(
    dataframe=val_data,
    x_col="image_path",
    y_col="label",
    target_size=(IMG_SIZE, IMG_SIZE),
    batch_size=BATCH_SIZE,
    class_mode="binary",
    shuffle=False
)

# Load MobileNetV2 without the final classification layer
base_model = MobileNetV2(
    input_shape=(IMG_SIZE, IMG_SIZE, 3),
    include_top=False,
    weights="imagenet"
)

# Freeze the base model layers
base_model.trainable = False

# Build the final model
mobilenet_model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation="relu"),
    layers.Dropout(0.5),
    layers.Dense(1, activation="sigmoid")
])

# Show model architecture
mobilenet_model.summary()

# Compile MobileNetV2 model
mobilenet_model.compile(
    optimizer="adam",
    loss="binary_crossentropy",
    metrics=["accuracy"]
)

# Train MobileNetV2 model
history_mobilenet = mobilenet_model.fit(
    mobilenet_train_images,
    validation_data=mobilenet_val_images,
    epochs=5
)

# Evaluate MobileNetV2 model on validation data
mobilenet_loss, mobilenet_accuracy = mobilenet_model.evaluate(mobilenet_val_images)

print("MobileNetV2 Validation Loss:", mobilenet_loss)
print("MobileNetV2 Validation Accuracy:", mobilenet_accuracy)

# Create a comparison table between CNN and MobileNetV2
import pandas as pd

comparison_df = pd.DataFrame({
    "Model": ["CNN from Scratch", "MobileNetV2"],
    "Validation Loss": [cnn_loss, mobilenet_loss],
    "Validation Accuracy": [cnn_accuracy, mobilenet_accuracy]
})

display(comparison_df)

# Generate predictions using CNN model
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix

# Reset validation generator
val_images.reset()

# Predict probabilities
cnn_predictions = cnn_model.predict(val_images)

# Convert probabilities to class labels
cnn_pred_classes = (cnn_predictions > 0.5).astype("int32").flatten()

# True labels
true_classes = val_images.classes
# Class names
class_names = list(val_images.class_indices.keys())

print("CNN Classification Report:")
print(classification_report(true_classes, cnn_pred_classes, target_names=class_names))

# Generate predictions using MobileNetV2 model
mobilenet_val_images.reset()

# Predict probabilities
mobilenet_predictions = mobilenet_model.predict(mobilenet_val_images)

# Convert probabilities to class labels
mobilenet_pred_classes = (mobilenet_predictions > 0.5).astype("int32").flatten()

# True labels
mobilenet_true_classes = mobilenet_val_images.classes

# Class names
mobilenet_class_names = list(mobilenet_val_images.class_indices.keys())

print("MobileNetV2 Classification Report:")
print(classification_report(mobilenet_true_classes, mobilenet_pred_classes, target_names=mobilenet_class_names))

# Confusion Matrix for CNN model
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

cnn_cm = confusion_matrix(true_classes, cnn_pred_classes)

disp = ConfusionMatrixDisplay(confusion_matrix=cnn_cm, display_labels=class_names)
disp.plot()
plt.title("CNN Confusion Matrix")
plt.show()

# Confusion Matrix for MobileNetV2 model
mobilenet_cm = confusion_matrix(mobilenet_true_classes, mobilenet_pred_classes)

disp = ConfusionMatrixDisplay(confusion_matrix=mobilenet_cm, display_labels=mobilenet_class_names)
disp.plot()
plt.title("MobileNetV2 Confusion Matrix")
plt.show()

# Final results summary
print("Final Model Comparison")
print("----------------------")
print("CNN Validation Accuracy:", round(cnn_accuracy, 4))
print("CNN Validation Loss:", round(cnn_loss, 4))
print("MobileNetV2 Validation Accuracy:", round(mobilenet_accuracy, 4))
print("MobileNetV2 Validation Loss:", round(mobilenet_loss, 4))

if cnn_accuracy > mobilenet_accuracy:
    print("\nBest Model: CNN from Scratch")
else:
    print("\nBest Model: MobileNetV2")

# Save the best performing model
cnn_model.save("best_glasses_classification_cnn_model.h5")

print("Best CNN model saved successfully.")

"""## Conclusion

In this project, a binary image classification system was developed to classify face images into two categories: Glasses and No_Glasses. The dataset was downloaded from Kaggle and prepared using image paths and class labels from the training CSV file. The images were resized to 224 × 224 pixels and processed using data augmentation techniques such as rotation, zooming, and horizontal flipping to reduce overfitting.

Two deep learning models were implemented and compared. The first model was a Convolutional Neural Network built from scratch, while the second model used MobileNetV2 as a pre-trained transfer learning model. The CNN model achieved a validation accuracy of approximately 88.56%, while MobileNetV2 achieved approximately 87.22%. Based on these results, the CNN model performed slightly better for this dataset.

The results show that CNNs are effective for binary image classification tasks. Future improvements could include fine-tuning the MobileNetV2 layers, using more epochs, applying stronger augmentation, or testing other pre-trained models such as VGG16, ResNet50, or EfficientNet.
"""